### ISSUE TITLE
Fail with accentuated chars in the file name on Mac OS X

### ISSUE THREAD

**Issue by Fil** [predat/wetransferpy#1]
```
wetransfer-upload planète\ Mars.jpg
Upload file : planète Mars.jpg
Traceback (most recent call last):
  File "/usr/local/bin/wetransfer-upload", line 48, in <module>
    url = w.uploadFile(it)
  File "/usr/local/lib/python2.7/site-packages/wetransferpy/wetransfer.py", line 207, in uploadFile
    fileMimeType, chunkNumber-1, fileSize)
  File "/usr/local/lib/python2.7/site-packages/wetransferpy/wetransfer.py", line 147, in _upload_chunk
    e = MultipartEncoder(fields=dataChunkUpload)
  File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 119, in __init__
    self._prepare_parts()
  File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 240, in _prepare_parts
    self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
  File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 230, in _iter_fields
    field.make_multipart(content_type=file_type)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/fields.py", line 173, in make_multipart
    (('name', self._name), ('filename', self._filename))
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/fields.py", line 133, in _render_parts
    parts.append(self._render_part(name, value))
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/fields.py", line 113, in _render_part
    return format_header_param(name, value)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/fields.py", line 37, in format_header_param
    result.encode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 15: ordinal not in range(128)
```

**Comment by predat** [comment]
I've not update wetransferpy on PyPI yet. You've to install wetransferpy from github if you want the fix.
