### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by 0xtf** [predat/wetransferpy#5]
Good evening,

Is the tool still working with whatever version WeTransfer API is at the moment? I'm currently using latest stable version and can't get pass the information "Upload file : ". No error, but no upload either.

This is under a unauthenticated upload. 

Thank you.

**Comment by 0xtf** [comment]
Just to add that the operation did time out, returning the error:

`Traceback (most recent call last):
  File "/usr/local/bin/wetransfer-upload", line 48, in <module>
    url = w.uploadFile(it)
  File "/usr/local/lib/python2.7/dist-packages/wetransferpy/wetransfer.py", line 194, in uploadFile
    self.transfer_id = self._get_transfer_id()
  File "/usr/local/lib/python2.7/dist-packages/wetransferpy/wetransfer.py", line 91, in _get_transfer_id
    r = self.session.post(WE_TRANSFER_API_URL, data=dataTransferId)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
OpenSSL.SSL.SysCallError: (104, 'Connection reset by peer')`

**Comment by 0xtf** [comment]
WeTransfer informed that they no longer support an API.
